[package]
edition = "2021"
name = "server"
version = "0.1.0"

[dependencies]
rand = "^0.7.0"
sol-ctf-framework = {git = "https://github.com/otter-sec/sol-ctf-framework.git", branch = "rewrite-v2"}
solana-program = "1.18.2"
solana-program-test = "1.18.2"
solana-sdk = "1.18.2"
anchor-lang = "0.29.0"
spl-token = "4.0.0"
tokio = "1.36.0"
zerocoin = {path = "../chall", features = ["no-entrypoint"]}
