#!/bin/sh

qemu-system-x86_64 \
	-m 128M \
	-smp 2 \
	-kernel bzImage \
	-initrd initramfs.cpio.gz \
	-append "console=ttyS0 kaslr kpti=1 panic=1 slab_nomerge panic_on_oops=1" \
	-snapshot -monitor /dev/null -nographic -no-reboot \
	-cpu qemu64,+smep,+smap
