#!/bin/bash
BASE=$(basename "$(pwd)")
FILES=(
	"Dockerfile"
	"Makefile"
	"lamp.c"
	"lamp"
	"run"
	"libc.so.6"
	"ld-linux-x86-64.so.2"
)
DIST=$(for FILE in "${FILES[@]}"; do echo "$BASE/$FILE"; done)
echo "flag{not_the_real_thing}" > /tmp/flag.txt
cd ..
tar -czf "$BASE/dist.tar.gz" $DIST \
	--transform "s|flag.txt|$BASE/flag.txt|" -C /tmp flag.txt
