const openings = [
  { name: 'Ruy Lopez', moves: 'e4 e5 nf3 nc6 bb5 a6 ba4 nf6 0-0 be7 re1 b5 0-0' },
  { name: 'Italian Game', moves: 'e4 e5 nf3 nc6 bc4 nf6 d3 d6 0-0 0-0' },
  { name: 'Sicilian Defense', moves: 'e4 c5 nf3 d6 d4 cxd4 nxd4 nf6' },
  { name: 'French Defense', moves: 'e4 e6 d4 d5 nd2 nf6 e5 nfd7' },
  { name: 'Caro-Kann Defense', moves: 'e4 c6 d4 d5 exd5 cxd5 nd2 nf6 ngf3 e6' },
  { name: 'Scotch Game', moves: 'e4 e5 nf3 nc6 d4 exd4 nxd4 bc5' },
  { name: 'King\'s Gambit', moves: 'e4 e5 f4 exf4 nf3 g5 d4' },
  { name: 'Queen\'s Gambit', moves: 'd4 d5 c4 e6 nc3 nf6 bg5 be7 e3 0-0' },
  { name: 'Slav Defense', moves: 'd4 d5 c4 c6 nc3 nf6 e3 e6' },
  { name: 'Grunfeld Defense', moves: 'd4 nf6 c4 g6 nc3 d5' },
  { name: 'Nimzo-Indian Defense', moves: 'd4 nf6 c4 e6 nc3 bb4' },
  { name: 'Queen\'s Indian Defense', moves: 'd4 nf6 c4 b6 nc3 e6' },
  { name: 'King\'s Indian Defense', moves: 'd4 nf6 c4 g6 nc3 bg7' },
  { name: 'Dutch Defense', moves: 'd4 f5 c4 nf6 nc3 e6' },
  { name: 'English Opening', moves: 'c4 e5 nf3 nc6 d4 exd4' },
  { name: 'Réti Opening', moves: 'nf3 d5 c4 c6 g3' },
  { name: 'Barne\'s Opening', moves: 'f4 e5 fxe5 qh4+ g3 qxe5+ be2' },
  { name: 'Grob\'s Attack', moves: 'g4 d5 Bg2 Bxg4' },
  { name: 'Ware Opening', moves: 'a4 e5 nf3 nc6 d4 exd4' },
  { name: 'Van \'t Kruijs Opening', moves: 'e3 e5 nf3 nc6 d4 exd4' },
  { name: 'Mieses Opening', moves: 'd3 e5 nf3 nc6 d4 exd4' },
  { name: 'Larsen\'s Opening', moves: 'b3 e5 nf3 nc6 d4 exd4' },
  { name: 'Dunst Opening', moves: 'nc3 e5 nf3 nc6 d4 exd4' },
  { name: 'Saragossa Opening', moves: 'c3 e5 nf3 nc6 d4 exd4' },
  { name: 'Albin Countergambit', moves: 'd4 d5 c4 c5 dxc5 e6' },
  { name: 'Chigorin Defense', moves: 'd4 d5 c4 nc6' },
  { name: 'Symmetrical Defense', moves: 'd4 d5 c4 c5' },
  { name: 'Tarrasch Defense', moves: 'd4 d5 c4 e6' },
  { name: 'Marshall Defense', moves: 'd4 d5 c4 c6' },
  { name: 'Bogo-Indian Defense', moves: 'd4 nf6 c4 e6 bf4' },
  { name: 'Catalan Opening', moves: 'd4 nf6 c4 e6 g3' },
  { name: 'Queen\'s Pawn Game', moves: 'd4 d5' },
  { name: 'Colle System', moves: 'd4 nf6 c3 e6' },
  { name: 'Torre Attack', moves: 'd4 nf6 c3 d5' },
  { name: 'London System', moves: 'd4 nf6 c3 e6 bf4' },
];

module.exports.openings = openings;
